services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    env_file:
      - ./postgres/.env
  
  tokens:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 80:8080
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432